"C#":
 - ./**/*.cs
 - ./**/*.csproj

"C# Project":
 - ./**/*.csproj

"C# Solution":
 - ./**/*.sln

"Powershell":
 - ./**/*.ps1
 - ./**/*.psm1

"SQL":
 - db/**/*
 - ./**/*.sql

"Solidity":
 - ./**/*.sol

"unit-tests":
 - src/*.Tests.*/**/*
 - src/*.Tests/**/*
 - src/*.Tests.Integration.*/**/*
 - src/*.Tests.Integration/**/*

".NET update":
 - src/global.json

"Config Change":
 - !src/global.json
 - src/**/*.json

"Static Code Analysis Rules":
 - src/CodeAnalysis.ruleset

"Migration Script":
 - tools/MigrationScripts/**/*

"Legal Text":
 - tools/LegalText/**/*

"Change Log":
 - CHANGELOG.md

"Read Me":
 - README.md

"Setup":
 - SETUP.md

"Markdown":
 - ./**/*.md

"github-actions":
 - .github/workflows/*.yml

"FunFair.BuildVersion":
 - src/FunFair.BuildVersion/**/*

"FunFair.BuildVersion.Detection":
 - src/FunFair.BuildVersion.Detection/**/*

"FunFair.BuildVersion.Detection.Tests":
 - src/FunFair.BuildVersion.Detection.Tests/**/*

"FunFair.BuildVersion.Interfaces":
 - src/FunFair.BuildVersion.Interfaces/**/*

"FunFair.BuildVersion.Publishers":
 - src/FunFair.BuildVersion.Publishers/**/*

"FunFair.BuildVersion.Publishers.Tests":
 - src/FunFair.BuildVersion.Publishers.Tests/**/*

"prepublish":
 - src/prepublish/**/*

